name = "demo_julia"
uuid = "618ed6bc-ca70-42ec-a910-e7485f1fd021"
authors = ["AlfredSAM <alfred.cenhui@gmail.com>"]
version = "0.1.0"

[deps]
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
